language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t pankajbhadauriya121/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pankajbhadauriya121/docker-react npm run test
